### ISSUE TITLE
No function to reset text buffer for XTextBox

### ISSUE THREAD

**Issue by ALittleSlow** [ImpulseAdventure/GUIslice#12]
In GUISlice_ex, we are missing a function to reset the buffer of the XTextBox element.

Cal has proposed:
It should be easy to add a gslc_ElemXTextboxReset(pElem) which would perform something like the following:
gslc_tsXTextbox* pBox;
pBox = (gslc_tsXTextbox*)(pElem->pXData);
pBox->nBufPosX = 0
pBox->nBufPosY = 0
memset(pBox->pBuf,0,pBox->nBufRows*pBox->nBufCols*sizeof(char));
gslc_ElemSetRedraw(pElem,GSLC_REDRAW_INC)

**Comment by ImpulseAdventure** [comment]
Thanks for pointing out this missing functionality. I have now added it to `GUIslice_ex.*`

Function `gslc_ElemXTextboxReset()` added by https://github.com/ImpulseAdventure/GUIslice/commit/851b16bdefe861b508dba356ef1a8f61d382d4d1
