### ISSUE TITLE
ESP8266 with Arduino Mega 2560

### ISSUE THREAD

**Issue by SyedFaisal** [ImpulseAdventure/GUIslice#13]
I am using ESP8266-01 with Arduino Mega 2560...i want to know how to send user-defined data to a server, if for example my website name is "www.mysite.com" and my php file there is "receive.php", and the whole link of php looks like ,
www.mysite.com/project/receive.php           where i receive one value in string form
How will i do the code for posting this to web server? please help with hint codes

**Comment by ImpulseAdventure** [comment]
Hi Syed --

The `GUIslice` library is focused primarily on the graphical display functionality of the Arduino, so my assistance may be a bit limited. Nonetheless, I recommend you start by using a `HTTP GET` methodology to send data from the ESP8266 to your webserver (as this makes testing much easier). Many examples of this approach can be found on the web; here is one example: http://www.instructables.com/id/ESP8266-Building-Blocks-Send-Data-to-a-Web-Server-/

Hope that helps!
