### ISSUE TITLE
Update the installation guide

### ISSUE THREAD

**Issue by rtek1000** [ImpulseAdventure/GUIslice#132]
Hello,

I think it is necessary to update the installation guide, because it seems that the 64-bit version is no longer available (although 32-bit linux versions are being deprecated: https://www.makeuseof.com/tag/why-linux-distros-ending-32-bit/)

Thank you.

Image attached:

https://github.com/ImpulseAdventure/GUIslice/wiki/Builder-_-Installation-_-Windows

> In the latest Release Notes under Assets, you will find builder-**_win64_**-X.Y.Z.zip

https://github.com/ImpulseAdventure/GUIslice/releases

> builder-**_win_**-0.11.0-rc4.zip

![guide win64](https://user-images.githubusercontent.com/8660811/55930492-ddef2d80-5bf7-11e9-90a5-10303df59308.jpg)

**Comment by ImpulseAdventure** [comment]
Good catch. Yes, the Builder Windows executable is no longer specific to 64-bit Windows, so it is now named `Builder-win-*.zip` instead of `Builder-win64-*.zip`. Wiki has been updated.
