### ISSUE TITLE
Builder: Missing template: <FONT_INCLUDE>

### ISSUE THREAD

**Issue by mrbloozman** [ImpulseAdventure/GUIslice#164]
I just tried builder 0.13 (linux version), upon code generation I receive an error message: builder.codegen.CodeGenException: Missing template: <FONT_INCLUDE>

GUIsliceBuilder/templates only contains c.t and ino.t along with the font spreadsheets, is there supposed to be more?

**Comment by ImpulseAdventure** [comment]
Thank you @mrbloozman for noting this! I have recreated the same issue in my LINUX VM. I believe the issue is just a missing section in an internal LINUX template resource (`linux.t`); I'll let @Pconti31 take a look at it in more detail. thx

**Comment by Pconti31** [comment]
The FONT_INCLUDE template isn't used when you target linux platform.
This template is only used by arduino.  The code was incorrectly trying to open
FONT_INCLUDE before testing for linux.
Fixed in 0.13.0.1 which is  available in the GUIslice-Builder-source repository releases.
Calvin will update the GUIslice API releases as soon as possible.

Paul--

**Comment by mrbloozman** [comment]
Thanks @ImpulseAdventure and @Pconti31 for looking into this.  I've installed 0.13.0.1 and tried generating code again.  Now I'm getting a fatal crash (see attached log).

[20190819_215256.txt](https://github.com/ImpulseAdventure/GUIslice/files/3518769/20190819_215256.txt)

Let me know if I can provide more information.

**Comment by Pconti31** [comment]
Thanks for your report.  However, to hunt down the problem I need a zip file of your project folder.
It contains the *.prj file we are trying to generate code for.  Without it I have no idea what is doing on.
Thanks.

Paul--

**Comment by mrbloozman** [comment]
Ah, that's a good hint.  I found an older c file that was generated by a prior version of the builder, which I removed, then regenerated a fresh c file with no issues.  Thanks for these very useful tools.

**Comment by ImpulseAdventure** [comment]
Thank you @mrbloozman for the followup. For future reference, Paul had identified the issue with the Builder's import of older Builder-generated projects; this should now be fixed in the Builder hotfix release `0.13.0.2`.
