### ISSUE TITLE
Can the spinner arrows be reversed?

### ISSUE THREAD

**Issue by spiff72** [ImpulseAdventure/GUIslice#190]
### Feature Request or Enhancement
I am no expert in GUI design, but for some reason, I expected that the down (decrement) button on the spinner would be on the left, and the up (increment) spinner would be on the right.  Can this be added as an option in the spinner?

### Additional context
This is just a "nice to have" feature for me.  I just found this GUISlice and created a working GUI for a printer enclosure exhaust fan control in 1 day - completely solving my issue of figuring out how to debounce touchscreen buttons!  

Thanks for building this tool - it is amazing!

**Comment by ImpulseAdventure** [comment]
Hi @spiff72 -- glad to hear the tool has been useful! Your request seems reasonable. I anticipate we might find people who prefer both placement orders :)

We could add an option for this; it would likely require an extra widget parameter setting in the Builder and an updated API. In the meantime, you should be able to change your existing **XSpinner** widget to work in the way you have requested with the following modification to your `/elem/XSpinner.c` file: (see the red highlights for changes)

![image](https://user-images.githubusercontent.com/8510097/72874742-8f52e180-3ca7-11ea-9939-918c74a5fddc.png)

Let me know if that works

**Comment by spiff72** [comment]
Thanks!  I will give that a shot later.

**Comment by spiff72** [comment]
Oops - wait a minute - what you show above is already exactly what my XSpinner.c file shows.  Are you saying that I need to swap the INC and DEC and the /030 and /031?

**Comment by ImpulseAdventure** [comment]
Great! Thanks for confirming that it works. I will close this for now, but can reopen it if it looks like integrating the added flexibility into the Builder / APIs seems worthwhile.
