### ISSUE TITLE
ERROR: GSLC_SD_EN required for this example but not enabled. Please update GUIslice config

### ISSUE THREAD

**Issue by Deltaplc** [ImpulseAdventure/GUIslice#192]
Good morning
I just approached this library and was trying to compile the sample sketches but with example number 3 it gives me this error! I went to GUIslice_config_ard.h and set the value 1
#define GSLC_SD_EN 1
but nothing has changed!
Can you help me?
I would like to operate an ILI9341 tft lcd with integrated sd, can you give me some advice on the configuration?
Thank you

**Comment by ImpulseAdventure** [comment]
Hi @Deltaplc --

You're on the right track, but it looks like the wrong config file may have been modified.

Which GUIslice config have you selected (uncommented) in `/src/GUIslice_config.h`?
Note that `/src/GUIslice_config_ard.h` is a default/deprecated config file that is no longer used, so we shouldn't need to modify it.

Instead, let's find a good example config to start from and then make the modification there instead.

I'm not sure which board/MCU you are using and which ILI9341 display you have (if you could provide links to them, that would be helpful), but let's assume it is the **Adafruit 2.8" resistive TFT** on an **Arduino/ATmega2560**.

If so, you would uncomment the following line in `/src/GUIslice_config.h`:
```c++
#include "../configs/ard-shld-adafruit_28_res.h"
```
Then, you would modify `/configs/ard-shld-adafruit_28_res.h`:
```c++
#define GSLC_SD_EN    1
```

**Comment by Deltaplc** [comment]
[2.4inch-TFT-UserManual-CN.zh-CN.it.pdf](https://github.com/ImpulseAdventure/GUIslice/files/4166585/2.4inch-TFT-UserManual-CN.zh-CN.it.pdf)

Hello
Thank you so much for your answer.
I tried to do as you said, but unfortunately the error persists !!!
I have attached the pdf file of the LCD that I have to control (if possible with Arduino Uno).
I have already made it work with the MCUFRIEND_kbv and Adafruit_GFX, Adafruit_TFTLCD library and everything works.
If you can give me some advice for the configuration I would be grateful!
Thank you

**Comment by ImpulseAdventure** [comment]
I am surprised that you are observing that error, as it suggests to me that the config file you are editing is not the same one that is being loaded by the Arduino IDE. Tomorrow I will try retesting it on my end too just in case I overlooked something.

Given the link you provided, I believe the most suitable configuration for your hardware might be `/configs/ard-shld-mcufriend_4wire.h`

Please try the following and let me know briefly what steps 3, 4 and 6 do:
1) Modify `/src/GUIslice_config.h` to uncomment only the line with: `ard-shld-mcufriend_4wire.h`
2) Modify `/configs/ard-shld-mcufriend_4wire.h` to change GSLC_SD_EN from 0 to 1
3) Compile & run GUIslice example /arduino/ex02_ard_btn_txt.ino. Does it compile & run OK?
4) Compile & run GUIslice example /arduino/ex03_ard_btn_img.ino. Does it compile & run OK?
5) Modify `/configs/ard-shld-mcufriend_4wire.h` to insert the following line at the top (eg. line 4):
```c++
#error "Loading the MCUFRIEND config!"
```
6) Compile & run GUIslice example /arduino/ex03_ard_btn_img.ino. Does it compile & run OK? You should see it fail with the error message "Loading the MCUFRIEND config!" If the Arduino IDE doesn't report this, then we know the IDE is not loading the right config file!

thanks

**Comment by Deltaplc** [comment]
Hello
I did everything you recommended and everything went well!
Now no longer gives the error for the SD configuration. All right! It may be that I made some mistakes yesterday.
Thank you very much for your help, now I will try to connect my LCD and I will make my first tests with the GUIslice Builder application, I hope to be able to make everything work!
Thanks again!

**Comment by ImpulseAdventure** [comment]
Good to hear it's all working. Thanks for the followup!

**Comment by Tizfaver** [comment]
> Good to hear it's all working. Thanks for the followup!

I have Blank screen with tft 3.5 "ILI9486 / ILI9488 / HX8357D

Hi I bought this display: [this](https://www.amazon.it/dp/B07PLQS8MT/ref=pe_24968671_487022601_TE_SCE_dp_1)
In the back of the shiled is written that thew drivers are: ILI9488, ILI9486, HX8357D

I installed all libraries: Adafruit GFX, mcufriend, GUIslice-master

After this, I uncommented in /src/GUIslice_config.h the line that have #include "../configs/ard-shld-mcufriend_4wire.h", and after that i changed in the file /config/ard-shld-mcufriend_4wire.h the line that have #define GSLC_SD_EN 0 in #define GSLC_SD_EN 1

Anrduino IDE run the code without problems, no error, nothing... the problem is that the screen is blank, and i don't see nothing.
But with the example GLUE_Demo_480x320 from the library MCUFRIEND_kbv the screen works.

Can somebody help me?
