### ISSUE TITLE
[Solved]Request:Add a overlay layer for xkeypad

### ISSUE THREAD

**Issue by Lucy2003** [ImpulseAdventure/GUIslice#194]
When I use gslc_PopupShow to show a info window (there is a textinput in the info window),and when I want to input something,the keypad is shown and the info window is hidden. The keypad is using the overlay layer so the info window has to been hidden.I think:
   **Could you please add a overlay layer (Top most) for the keypad or can I make it work in other way?**

Thanks.

**Comment by Pconti31** [comment]
Hello Lucy. 
I wrote the original keypad that Calvin then modified for release.  Last august I submitted
a much better version that more closely looks like the android keyboards that takes up less screen space and memory and also adding a button to switch between number keypad, letters and symbols.
Hopefully, Calvin will someday add it to the API.

As for your problem we don't really need to mod the API for more overlays.  Just use them more wisely.  

I have attached a solution example for you that asks a question then display an answer (dummy of course).  Hopefully it will be enough of an example to help you out.

The key to whole thing is inside the CbKeypad callback:
`      case E_INPUT_QUESTION:`
You simply need to add a line to re-display your popup info screen with whatever anwser lookup
you need to provide after hiding the keypad popup as so:
`      case E_INPUT_QUESTION:`
`        gslc_ElemSetTxtStr(pGui, m_pElemQuestion, gslc_ElemXKeyPadDataValGet(pGui, pvData)); `
`        gslc_PopupHide(&m_gui);`
`       gslc_ElemSetTxtStr(pGui, m_pElemAnswer,"Dummy Answer"); `
`       gslc_PopupShow(&m_gui, E_PG_POPUP_INFO, true);`
`      break;`

Paul--
[ex_popup_input.zip](https://github.com/ImpulseAdventure/GUIslice/files/4181469/ex_popup_input.zip)
