### ISSUE TITLE
Build a header file instead of .ino

### ISSUE THREAD

**Issue by Pconti31** [ImpulseAdventure/GUIslice#209]
Lucy2003 opened issue#72 in the Builder's repository concerning the builder
breaking the *.ino file into two pieces .  
While this seems simple enough I could use some feedback on the implementation.

And since very few people watch the builder I decided to cross post here.

If you care to comment please go directly to the Builder issue page
[https://github.com/ImpulseAdventure/GUIslice-Builder/issues/72](url)

Paul--

**Comment by Lucy2003** [comment]
[https://github.com/ImpulseAdventure/GUIslice-Builder/issues/72](https://github.com/ImpulseAdventure/GUIslice-Builder/issues/72)

**Comment by Pconti31** [comment]
Fixed in release 0.13.b021
