### ISSUE TITLE
request to implement gslc_ElemXListboxDelItem

### ISSUE THREAD

**Issue by Avpi18** [ImpulseAdventure/GUIslice#224]
it would be very convenient if an item can be removed from a listbox by a user. Select an item from a listbox and delete it with a command (e.g. `gslc_ElemXListboxDelItem`).
I'm brand new and apologize if I make the odd mistake

**Comment by ImpulseAdventure** [comment]
Hi @Avpi18 -- yes, this would be a good feature to implement. I have an open feature request in #205 for this same item, so will close this as a duplicate, and increase the priority to get it implemented!

Thanks
