### ISSUE TITLE
Text string element

### ISSUE THREAD

**Issue by giordy72** [ImpulseAdventure/GUIslice#233]
Hi,
I can't make text string works well.
I want to update a value on the screen once per second, so I wrote this inside my loop:
```
   _gslc_ElemSetTxtStr(&m_gui, m_pElemOutTxtStatus,acTxt);    
   snprintf(acTxt,MAX_STR,(char*)"RPM = %4u\n",speedRead);_
```
This works...but the string didn't update well mixing all the new updated strings together.

![IMG_20200522_145610](https://user-images.githubusercontent.com/20452696/82669930-916c8300-9c3c-11ea-8a4f-5af6939a99c8.jpg)

 `char acTxt[21];` is defined at the beginning of loop().

Have I missed something? Suggestions?

**Comment by ImpulseAdventure** [comment]
Hi @giordy72 -- it looks like you are doing everything correctly with the updates.

What the output above usually means is that the size of the text element wasn't large enough to contain all of the text (including the RPM value updates). To keep things efficient, the element dimensions dictate where redraws will be done.

Look for the dimensions in the `gslc_ElemCreateTxt()` call. In the example below, we would increase the 44 which defines the width: 
```c++
pElemRef = gslc_ElemCreateTxt(&m_gui,E_ELEM_TXT_COUNT,E_PAGE_MAIN,(gslc_tsRect){80,60,44,12},(char*)m_sDisplayText2,8,E_FONT_TXT5);
```

If you are using the Builder, then the text element size is normally estimated by the  "External Storage Size" setting and the current font. Please try increasing the width to see if that helps.

Ideally, if you could ZIP up your project folder, with any builder and generated sketch file and attach to this issue, it may help me see how you are creating the element.

thanks

**Comment by ImpulseAdventure** [comment]
Closing based on the assumption that the text element needed to be larger to accommodate the text updates. @giordy72 if at some point you are able to confirm, that would be great. If the problem remains, I will reopen the issue for you. thanks.

**Comment by giordy72** [comment]
Hi all,
gslc_ElemCreateTxt with the right settings (310pxl wide now!) solves the issue.
Thank's a lot
