### ISSUE TITLE
The 2.4-inch ILI9341 screen displays nothing, only gray

### ISSUE THREAD

**Issue by thisisausername-rgb** [ImpulseAdventure/GUIslice#240]
### Describe the bug
*The 2.4-inch ILI9341 screen displays nothing, only gray*
![1594457253026](https://user-images.githubusercontent.com/61218890/87220477-af31ab00-c396-11ea-98a4-f68a4760d7ff.jpg)

### Device hardware
- *MCU*: ESP32.
- *Display with link*: ILI9341 2.4
- *GUIslice config selected*:  `esp-tftespi-default-xpt2046`

### Checklist to try first
*Most display/touch issues can be identified by working through the steps in the [Configuring GUIslice](https://github.com/ImpulseAdventure/GUIslice/wiki/Configuring-GUIslice) guide.*

*Please confirm whether:*
- *Display works correctly with standalone display driver library examples (eg. TFT_eSPI graphicstest, Adafruit graphicstest, etc.) without GUIslice:* ???
TFT_eSPI graphicstest work 
![1594456628301](https://user-images.githubusercontent.com/61218890/87220408-f23f4e80-c395-11ea-8a8b-5d1db8c49e8f.jpg)

- *Touch works correctly with standalone touch library examples without GUIslice:* ???
TFI_eSPI+XPT2046_Touchscreen.h work
### Expected behavior
*A description of what you expected to happen*
Screen display GUI
### Initialization messages
*Please copy any startup messages / errors reported to the serial monitor window here. You can enable all error messages by setting `DEBUG_ERR 2` in the GUIslice config file.*
```
85$&P`N⸮⸮⸮Б.u⸮GUIslice version [0.14.0]:
- Init display handler [TFT_eSPI] OK
- Init touch handler [XPT2046_PS(SPI-HW)] OK
```
### Additional info
*Add any other context about the problem here.*

**Comment by Pconti31** [comment]
It might be helpful if you attached a zip file to this issue containing your config/esp-tftespi-default-xpt2046.h, src/GUIslice_config.h, src/GUIslice_version.h, and TFT_eSPI/User_Setup.h and your <whatever you compiled>.ino even if its a sample.
Paul--

**Comment by thisisausername-rgb** [comment]
[myfile.zip](https://github.com/ImpulseAdventure/GUIslice/files/4906809/myfile.zip)

**Comment by Pconti31** [comment]
While I don't think its your problem (we need to wait for Calvin's input for that) one thing I did notice is that your User_Setup.h is configured to use TFT_eSPI's internal touch driver.  In this case you should be using esp-tftespi-default-xpt2046_int.h as your config file.
Paul--

**Comment by thisisausername-rgb** [comment]
thanks a lot，after using esp-tftespi-default-xpt2046_int.h instead of esp-tftespi-default-xpt2046.h，My problem has been solved.
![1594564868103](https://user-images.githubusercontent.com/61218890/87249452-bbe6f980-c491-11ea-9746-688c3f14534d.jpg)

**Comment by SunboX** [comment]
hey @thisisausername-rgb I'm currently triying the exact same thing. But I don't get it to be working. Can you send me you setup / project as a starting point please? I don't know what I'm doing wront. Simple eSPI test runs fine, but I don't get it working using GUIslice.

**Comment by thisisausername-rgb** [comment]
> hey @thisisausername-rgb I'm currently triying the exact same thing. But I don't get it to be working. Can you send me you setup / project as a starting point please? I don't know what I'm doing wront. Simple eSPI test runs fine, but I don't get it working using GUIslice.




[TFT_eSPI.zip](https://github.com/ImpulseAdventure/GUIslice/files/5256053/TFT_eSPI.zip)

**Comment by SunboX** [comment]
Hm, that's the eSPI library. I know that one. ;) And I got it working with it. ;) But for some reason I can't get the GUIslice working with it. A small example would be nice, I guess I'm doing something wrong. But I don't know what.

**Comment by thisisausername-rgb** [comment]
> 嗯，这就是eSPI库。我知道那个。;）并且我可以使用它。;）但是由于某种原因，我无法让GUIslice使用它。一个小例子会很好，我想我做错了。但是我不知道。

[GUIslice.zip](https://github.com/ImpulseAdventure/GUIslice/files/5256755/GUIslice.zip)

here is a example built by guisliceBuilder
[SimpCount.zip](https://github.com/ImpulseAdventure/GUIslice/files/5256765/SimpCount.zip)

**Comment by Pconti31** [comment]
@SunBoX Did you comment out all references to TOUCH_CS inside TTFT_eSPI's User_Setup.h
and use GUIslice/config/ esp-tftespi-default-xpt2046_int.h inside GUIslice/src/GUIslice_Config.h?
Paul--

**Comment by SunboX** [comment]
I'm one step further ... now I'm getting those Exceptions:
```
.pio\libdeps\esp32dev\GUIslice\src\GUIslice_drv_tft_espi.cpp:1371:17: error: 'struct gslc_tsGui' has no member named 'nSwapXY'
       if (pGui->nSwapXY) {
                 ^
.pio\libdeps\esp32dev\GUIslice\src\GUIslice_drv_tft_espi.cpp:1377:19: error: 'struct gslc_tsGui' has no member named 'nFlipX'
         if (pGui->nFlipX) {
                   ^
.pio\libdeps\esp32dev\GUIslice\src\GUIslice_drv_tft_espi.cpp:1380:19: error: 'struct gslc_tsGui' has no member named 'nFlipY'
         if (pGui->nFlipY) {
                   ^
```

I'm using PlatformIO to run the code. Here's my project:
[Uploading DisplayTest (2).zip…]()

**Comment by SunboX** [comment]
Fixed it with https://github.com/ImpulseAdventure/GUIslice/issues/269
