### ISSUE TITLE
Flip toggle button

### ISSUE THREAD

**Issue by kinafu** [ImpulseAdventure/GUIslice#271]
### Enhancement
Currently the toggle button is implemented the other way around, than expected by me and probably most of the users.

When the button is checked, the slider/thumb should be on the right side.
The unchecked position should be on the left.

Why?
[Here you can check](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/switch), that Android and iOS handle the buttons in the same way like suggested in this issue.
Maybe the often used iOS and Android implementation is the reason why the currently implemented GUISlice button does not feel right for me.

Below you can see the current implementation on the left and my idea on the right.

<img src="https://user-images.githubusercontent.com/20564946/94193937-4778ff80-feb1-11ea-85b1-7913acebaf0e.png" width="400"  />

**Comment by ImpulseAdventure** [comment]
Hi @kinafu — it seems like a reasonable request to adopt the more conventional representation. @Pconti31 as you contributed the toggle button originally, let me know if you have any concerns with me proceeding to make this change.

**Comment by Pconti31** [comment]
@kinafu 
@ImpulseAdventure No Problem At my end.

**Comment by ImpulseAdventure** [comment]
Visuals swapped now in latest version on GitHub.
@kinafu - please let me know if the update works as requested.

**Comment by kinafu** [comment]
I just tried it out.
The change works for me as expected ✔️
