### ISSUE TITLE
Text background not transparent. ILI9341/TFT_eSPI

### ISSUE THREAD

**Issue by ASMotionLab** [ImpulseAdventure/GUIslice#273]
Hi,

I hope you can help me once again.

I'm not sure if this is a bug or user error, so I didn't mark this as a bug.

Text background is not rendering transparent, there is a black box behind the text when fill is set to **false**
The code is correct: gslc_ElemSetFillEn(&m_gui,pElemRef,false); In my case it's generated from GUIslice.

The image should explain the issue clearly:
![1601122720271s](https://user-images.githubusercontent.com/43951291/94340650-6e434d00-fffb-11ea-8b5c-aba475482a61.jpg)

Is this another ILI9341 bug? Or are there some settings i'm missing.

Thanks a huge bunch!

**Comment by ImpulseAdventure** [comment]
I will take a look to determine why the transparency doesn’t appear to be working in your example.

There could very well be an issue in the library for a particular display driver or font mode. Could you attach the following for me so I can narrow it down:
- Your sketch file
- Your user config (eg. esp-tftespi-default-xpt2046.h)
- If TFT_eSPI used, then your TFT_eSPI setup file referenced by User_Setup_Select.h
- What display model is being used (Ideally a link to the listing if you have it), and what MCU (eg. ESP32?)

Thanks!

**Comment by ASMotionLab** [comment]
Thank you, all attached!
[GitIssueTextBg.zip](https://github.com/ImpulseAdventure/GUIslice/files/5286822/GitIssueTextBg.zip)

**Comment by ImpulseAdventure** [comment]
Thanks @ASMotionLab -- in your TFT_eSPI User_Setup I see that `SMOOTH_FONT` has been enabled.
In this particular mode, it looks like there is an issue with transparent text output that needs fixing.

I haven't tested it yet, but I wonder if the following line added into GUIslice.cpp (additional line highlighted in blue) might help you to use SMOOTH_FONT mode: (alternately, commenting out SMOOTH_FONT in your user setup may work in the short term)
![image](https://user-images.githubusercontent.com/8510097/94350152-4dc9c180-0000-11eb-8b63-8f91c7f1dbaf.png)

I would be interested to hear if the above modification works for you. Nonetheless, I will continue on to test this mode later and report back.
thanks

**Comment by ASMotionLab** [comment]
Thanks @ImpulseAdventure 

With SMOOTH_FONT enabled:
Adding the colBg = pElem->colElemText; into GUIslice.c indeed works!
![1601205499346s-SMOOTHOnWithMod](https://user-images.githubusercontent.com/43951291/94363686-ce012d00-00bb-11eb-85f4-d1212a833e8d.jpg)

With SMOOTH_FONT disabled:
Background rendering works correctly by default like you suggested.
And works correct
![1601205499333s-SMOOTHOffNoMod](https://user-images.githubusercontent.com/43951291/94363689-d194b400-00bb-11eb-8d54-e8d46987018d.jpg)

I think I only enabled SMOOTH_FONT because that enabled SPIFFS for some example sketches I was trying.

Is there a performance penalty for having colBg = pElem->colElemText; in GUIslice.c by default?

**Comment by ASMotionLab** [comment]
Sorry, I used a different example to illustratoe my findings, Here's the original sketch:
![1601206019735s-SMOOTHOffNoMod](https://user-images.githubusercontent.com/43951291/94363842-f0477a80-00bc-11eb-8ac3-30e3f4e27e2b.jpg)

**Comment by ImpulseAdventure** [comment]
Great -- thank you for the tests! I have integrated the fix into the latest GUIslice.
There will be no additional performance impact with this change above TFT_eSPI's transparent text rendering.
