### ISSUE TITLE
M5Stack core can't build with arduino ide

### ISSUE THREAD

**Issue by huang443765159** [ImpulseAdventure/GUIslice#287]
NOTE: For issues with the GUIslice Builder, please file a report instead at:
https://github.com/ImpulseAdventure/GUIslice-Builder-source/issues
Hello, I am a new Arduino.
I am use M5Stack core with arduino, but when I build examples I always get err like this:
![image](https://user-images.githubusercontent.com/59813252/98232863-28ce5400-1f99-11eb-9524-a380d15030c2.png)
Am I missing something that I have to install？
Thanks.

**Comment by Pconti31** [comment]
@huang443765159 The error indicates GUIslice thinks you are configured for Arduino not M5Stack.
Did you read the wiki?
[Configure GUIslice for M5stack](https://github.com/ImpulseAdventure/GUIslice/wiki/Configure-GUIslice-for-M5stack)
Paul--

**Comment by ImpulseAdventure** [comment]
Hi @huang443765159 -- as Paul mentioned, it is likely that the configuration selected in `GUIslice_config.h` needs to be changed.

Please try selecting **esp-shld-m5stack.h** in `GUIslice_config.h` by uncommenting that line (and ensuring all other config lines are commented out):
![image](https://user-images.githubusercontent.com/8510097/98268385-4d96dd00-1f41-11eb-8d27-4eb11e205bcf.png)

Does that correct the issue for you?
thanks

**Comment by huang443765159** [comment]
Thanks for your reply. 
Sorry, I may have missed reading the document.I'll try to modify and build again.
