### ISSUE TITLE
Spinner Font built-in not working in linux

### ISSUE THREAD

**Issue by abhishek1028** [ImpulseAdventure/GUIslice#309]
Spinner is using built-in type fonts. These are not ttf file. so that i am unable to use it in Linux and other fonts ttf file not loaded symbol of increment and decrement. Please resolve it.
In src/elem folder xspinner.c file has acIncr for increment charactor but I am not getting how I can pass charactor in it

**Comment by Pconti31** [comment]
@abhishek1028 I documented this in my Builder FAQ
[FAQ](https://github.com/ImpulseAdventure/GUIslice-Builder/releases/tag/v0.16.b003)
Paul--

**Comment by abhishek1028** [comment]
Where in code I call gslc_ElemXSpinnerSetChars() please send me link

**Comment by abhishek1028** [comment]
Thanks for guidance

**Comment by abhishek1028** [comment]
I have used faq instructions but not getting character for Inc and Dec of spinner using freemono font

**Comment by abhishek1028** [comment]
I got it place of call function and fixed the issue thanks
