### ISSUE TITLE
Support for png 

### ISSUE THREAD

**Issue by awareness2015** [ImpulseAdventure/GUIslice#312]
### Feature Request or Enhancement
Is it possible to add support for png to the library?

**Comment by ImpulseAdventure** [comment]
Hi — sorry for the delay as I although I had written a reply a while back it looks like I must have missed submitting it.

Unfortunately PNG decoding can be fairly involved and usually involves maintaining a sizable memory buffer that makes it unrealistic for many “Arduino” platforms.

If possible, I suggest converting your images from PNG to BMP as this will minimize the memory overhead and also speed up the rendering considerably.

I will close this for now but mark for future enhancement. Hopefully the offline BMP conversion will address your needs.

thanks

**Comment by awareness2015** [comment]
Hi, GUIslice is very excellent.Thank you very much!
