### ISSUE TITLE
Display only Text

### ISSUE THREAD

**Issue by nawazawanswl** [ImpulseAdventure/GUIslice#362]
how can i change "DISPLAY ONLY TEXT"  at runtime ?

**Comment by ImpulseAdventure** [comment]
Hi @nawazawanswl --

Please see the [GUIslice Builder Walkthrough](https://github.com/ImpulseAdventure/GUIslice/wiki/Builder-_-Walkthrough) tutorial as it will show you how you can update text fields at runtime.
