### ISSUE TITLE
Request: Text wrap within elements

### ISSUE THREAD

**Issue by ImpulseAdventure** [ImpulseAdventure/GUIslice#40]
The existing `ElemCreateTxt` and `ElemCreateBtnTxt` elements render a single line of text.
This request is to explore the possibility of providing some degree of text wrap functionality.

I would propose the following capabilities (in order of decreasing priority):
- [x] Support a manual forced-wrap via insertion of <code>\n</code> in the text string, enabling multi-line text
- [ ] Support default font (monospaced) as well as extended fonts (proportional)
- [ ] Support a character wrap mode based on the element bounds
- [ ] Consider an optional mode to support word-wrap rather than character-wrap

**Comment by Akrai** [comment]
Hi! I tried adding \n inside the string of a text and inside a text button label, but neither of those works, can I have some kind of text wrapping in a button?
