### ISSUE TITLE
Trigger the "Common Button callback" by code without having a real touch event?

### ISSUE THREAD

**Issue by kellers76** [ImpulseAdventure/GUIslice#419]
hello Calvin,

I want to run a WebServer parallel with my TFT in which I want to operate certain functions.
As an example I want to have the same button on the TFT and also on the web Page.

My question would be:

Is there a possibility to trigger the call "Common Button callback" also by code without having a real touch event?

According to my understanding I would get the button info (e.g. "E_ELEM_BTN9") from the Web Page, because I know the button I pressed.
With this value I would like to trigger the "Common Button callback" routine and execute the code stored there.

This would save me a lot of program code.

Do you see a possibility for this?
Would be great if you have an approach for me....

Thanks a lot

stefan

Translated with www.DeepL.com/Translator (free version)

**Comment by Pconti31** [comment]
@kellers76 Not sure exactly how much functionality you really need for what you are  doing but in the specific case you mentioned you could create a element reference to Button 9 (or any other ones you want) and simply call cbBtnCommon.
example:
```
//<Save_References !Start!>
gslc_tsElemRef* m_pElemBtn9       = NULL;
//<Save_References !End!>

  gslc_teTouch dummy_touch = GSLC_TOUCH_UP_IN;
  (void)cbBtnCommon((void*)m_pElemBtn9, dummy_touch, 0, 0);
```

I can't say this has any advantage to creating common functions that both cbBtnCommon case  E_ELEM_BTN9 and your web app call.  

Now if you are trying to traverse the TFT UI with buttons highlighted and data input from a web app then that's really complex and requires basic support from GUIslice much like Calvin has added for input buttons and is beyond my help.
Paul--

**Comment by kellers76** [comment]
hallo Paul,

thank you for answering so quickly.

The basic approach of you works!

I just tried to get the call executable....

With the following lines I don't get any error message when compiling, however the call doesn't seem to work properly yet:
//<Save_References !Start!>
gslc_tsElemRef* m_pElemBtn9 = NULL;
gslc_tsElemRef* m_pElemBtn10 = NULL;
gslc_tsElemRef* m_pElemBtn5 = NULL;
//<Save_References !End!>

  gslc_teTouch dummy_touch = GSLC_TOUCH_UP_IN;
  CbBtnCommon(&m_gui,m_pElemBtn9, dummy_touch, 0, 0);

With my m_pElemBtn9 on the web page I trigger a call, but the one for the m_pElemBtn10.
Also if I try another button with the m_pElemBtn5 the function of the m_pElemBtn10 is also triggered.


Maybe only a small thing is missing, so that I can execute the call correctly.


lg
stefan

**Comment by Pconti31** [comment]
@kellers76 if you post zip file of your attempt I'll do a quick desk check to see if I can determine the problem

**Comment by kellers76** [comment]
hallo Paul,

I have found my mistake.

I didn't fill the ElementRef in the builder and so the mapping didn't work correctly.

After I corrected this, your code works wonderfully!!!

Thanks a lot for your perfect support


best regards

stefan
