### ISSUE TITLE
m5stack ILI9341 not name a type

### ISSUE THREAD

**Issue by wuyuanyi135** [ImpulseAdventure/GUIslice#52]
Hi,

I am trying to use this library in a M5Stack board. I have configured the ard.h file to the proper options but the compilation failed because `ILI9341` does not exist.

It seems like M5Stack headers do not provide this class anymore. I replace the definition with the global display object and it worked.
```diff
-  ILI9341 m_disp = ILI9341();
+ #define m_disp m5.Lcd
```
Is this a bug? Probably the upstream library update broke the symbol.

**Comment by ImpulseAdventure** [comment]
Thank you, you're right... Looks like I didn't notice the updates to M5Stack. I have made a few changes and released [v0.10.3.](https://github.com/ImpulseAdventure/GUIslice/releases/tag/v0.10.3) Let me know if this works for you (as I am not able to test on M5Stack hardware at the moment, though I have tested the compilation).

**Comment by wuyuanyi135** [comment]
Looks good to me. Thank you!
