### ISSUE TITLE
gslc_ex05_ard.ino touch not working

### ISSUE THREAD

**Issue by moscowbob** [ImpulseAdventure/GUIslice#53]
Running this example on Feather M0 and Featherwing 2.4, the touch screen is not working.
Problem is the screen size return 0,0 after the extended components are created.

Problem is fixed by changing line 51
`#define MAX_ELEM_PG_EXTRA_RAM   MAX_ELEM_PG_MAIN  // # Elems in RAM` 
to
`#define MAX_ELEM_PG_EXTRA_RAM   MAX_ELEM_PG_EXTRA  // # Elems in RAM`

**Comment by ImpulseAdventure** [comment]
Thank you @moscowbob for catching this! Since `MAX_ELEM_PG_MAIN` > `MAX_ELEM_PG_EXTRA`, one wouldn't notice an issue until additional elements were created on the second page. I have updated the repo with the fix.
