### ISSUE TITLE
Pico W on TFT ILI9486 No TouchParallel with TFT_eSPI

### ISSUE THREAD

**Issue by GrandNagusQuark** [ImpulseAdventure/GUIslice#533]
### Describe the bug
I currently have a Pico W working with TFT_eSPI following the steps outlined in this thread: https://github.com/Bodmer/TFT_eSPI/discussions/2300

DMA graphics also work well.

 I configured the Guislice_config.h to #include "../configs/esp-tftespi-default-notouch.h"

I made a simple main page and created the code. When I upload to the pico, I only get a white screen.

Again, the tft_espi examples work great without issues.

- *MCU*: Pico W
- *Display with link*: HiLetgo 3.5" TFT LCD Display ILI9486/ILI9488 480x320 36 Pins for Arduino Mega2560 https://a.co/d/6NAlEhx
 *GUIslice config selected*:
/esp-tftespi-default-notouch.h"

### Additional info
I get an unknown platform error when I compile, that is the only error I get outside of Espi telling me I do not have touch configured so none of the touch features will work, which is fine as my screen is not touch.

**Comment by Pconti31** [comment]
@GrandNagusQuark Can you post your compiler errors for unknown platform.
This seems suspicious...
Edit your esp-tftespi-default-notouch.h file.
```
//  #define DEBUG_ERR               1   // 1,2 to enable, 0 to disable
  #define DEBUG_ERR               2   // 1,2 to enable, 0 to disable
//#define DBG_DRIVER        // Enable graphics driver debug reporting
#define DBG_DRIVER        // Enable graphics driver debug reporting`
```
and check the serial monitor output.
Paul--

**Comment by GrandNagusQuark** [comment]
Here is what I get:
```
//vvv
SPI::transfer(ff), cpol=0, cpha=0          // this repeats many many times
SPI: read back 00
//^^^
SPI::endTransaction()
SPI: IRQ masks = 00000000 00000000 00000000 00000002
#error: FS could not start
ERROR: DrvInit() SD init failed
- Init display handler [TFT_eSPI] FAIL
- No touch handler enabled
ERROR: Init() failed
```

**Comment by GrandNagusQuark** [comment]
I will also add that I looked into the SD options in my esp-tftespi-default-notouch.h and changed this to my SDCS pin:
```
  // -----------------------------------------------------------------------------
  // SECTION 2: Pinout
  // -----------------------------------------------------------------------------

  // For TFT_eSPI, the display wiring is defined by TFT_eSPI's User_Setup.h

  // SD Card
  //#define ADAGFX_PIN_SDCS    2 // ESP8266 + Adafruit FeatherWing 2.4"
  //#define ADAGFX_PIN_SDCS     14 // ESP32   + Adafruit FeatherWing 2.4"
  //#define ADAGFX_PIN_SDCS    5 // Others  + Adafruit FeatherWing 2.4"
  #define ADAGFX_PIN_SDCS     14 // << I connected my SDCS pin to this poin on Pico W

```

**Comment by GrandNagusQuark** [comment]
More info as I dig through the vast reaches of the interwebs (I have not put on my hacker glasses..... yet) I have found some info that I believe is relevant.

I am sure that the issue is that the SD card can not be accessed through the 16bit parallel connection to the LCD. The Screen has a SD_CS pin, and right next to it I see 3 SPI pins (MOSI, MISO, and CLK) but do not have any indication what that SPI hooks to. I do not know if the SPI pins are for SD card communication or as an option to connect to the display via SPI as an alternative. Also, as I really have not dealt much with external storage in the past, if I would just have to relocate my files onto the actual Pico instead of the display mounted SD card, how would I modify the resources section of the GSLC.h file as seen here:
```
// ------------------------------------------------
// Defines for resources
// ------------------------------------------------
//<Resources !Start!>
#define IMG_MILSBROLCDPIXILART9   "/milsbro-lcd-pixilart(9).bmp"
//<Resources !End!>
```

**Comment by GrandNagusQuark** [comment]
I got it working, just needed to do a nuke and pave. Now I have another issue. The letters I put in the Builder are not in the same place on the actual screen, they seem to be off vertically. Is this an odd quirk of the software?

**Comment by Pconti31** [comment]
@GrandNagusQuark Sounds like I have a problem with simulating a particular font in the Builder.  You can use my examples/builder/ex00_bld_fonttest/ex00_bld_fonttest.prj
Turn on Grid in the builder to show grid lines and a white background.
Use your problem font and place trhe text on grid lines.
Save and run the test app and see how things line up on your particular tft display.

Post followups in the [GUIslice-Builder/issues](https://github.com/ImpulseAdventure/GUIslice-Builder/issues) since this isn't my repository.
I will need your newly editted ex00_bld_fonttest project folder as a zip file and if possible a photo of your TFT display when you run your test and any additional information you can give me.
Paul--

**Comment by GrandNagusQuark** [comment]
Will do! I'll get that taken care of as soon as I am off work. I will mark this issue as solved.
