### ISSUE TITLE
Arduino UNO R3 + Waveshare 2.8 TFT Touch Screen result in error: 'HX8347D_kbv' 

### ISSUE THREAD

**Issue by gree303** [ImpulseAdventure/GUIslice#534]
### Describe the bug
Getting an error during compiling the following GUISlice for Arduino Example: ex02_ardmin_btn_txt.ino
`/home/admin/Arduino/libraries/GUIslice/src/GUIslice_drv_adagfx.cpp:359:3: error: HX8347D_kbv does not name a type; did you mean HX8347D_PINS_H_?
   HX8347D_kbv m_disp;`

### Device hardware
- Arduino Uno R3
- Waveshare 2.8inch TFT Touch Screen *version 1 / blank* [https://www.waveshare.com/2.8inch-tft-touch-shield.htm](https://www.waveshare.com/2.8inch-tft-touch-shield.htm)
- config:   #include "../configs/ard-shld-waveshare_28_touch.h"

I tested the TFT Screen with the basic Waveshare Example: Waveshare_HX8347D_kbv [https://github.com/prenticedavid/Waveshare_HX8347D_kbv](https://github.com/prenticedavid/Waveshare_HX8347D_kbv)

*Please confirm whether:*
- *Display works correctly with standalone display driver library examples (eg. TFT_eSPI graphicstest, Adafruit graphicstest, etc.) without GUIslice:* = Correct
- *Touch works correctly with standalone touch library examples without GUIslice:* = Correct

### Expected behavior
Won't compile, expected to compile and upload. Getting the following error:
`/home/admin/Arduino/libraries/GUIslice/src/GUIslice_drv_adagfx.cpp:359:3: error: 'HX8347D_kbv' does not name a type; did you mean 'HX8347D_PINS_H_'?
   HX8347D_kbv m_disp;
   ^~~~~~~~~~~
   HX8347D_PINS_H_
/home/admin/Arduino/libraries/GUIslice/src/GUIslice_drv_adagfx.cpp: In function 'bool gslc_DrvInit(gslc_tsGui*)':
/home/admin/Arduino/libraries/GUIslice/src/GUIslice_drv_adagfx.cpp:682:7: error: 'm_disp' was not declared in this scope
       m_disp.begin();
       ^~~~~~
/home/admin/Arduino/libraries/GUIslice/src/GUIslice_drv_adagfx.cpp: In function 'void* gslc_DrvGetDriverDisp(gslc_tsGui*)':
/home/admin/Arduino/libraries/GUIslice/src/GUIslice_drv_adagfx.cpp:784:19: error: 'm_disp' was not declared in this scope
   return (void*)(&m_disp);
                   ^~~~~~
/home/admin/Arduino/libraries/GUIslice/src/GUIslice_drv_adagfx.cpp: In function 'bool gslc_DrvGetTxtSize(gslc_tsGui*, gslc_tsFont*, const char*, gslc_teTxtFlags, int16_t*, int16_t*, uint16_t*, uint16_t*)':
/home/admin/Arduino/libraries/GUIslice/src/GUIslice_drv_adagfx.cpp:1151:5: error: 'm_disp' was not declared in this scope
     m_disp.setFont((const GFXfont *)pFont->pvFont);
     ^~~~~~
/home/admin/Arduino/libraries/GUIslice/src/GUIslice_drv_adagfx.cpp: In function 'bool gslc_DrvDrawTxt(gslc_tsGui*, int16_t, int16_t, gslc_tsFont*, const char*, gslc_teTxtFlags, gslc_tsColor, gslc_tsColor)':
/home/admin/Arduino/libraries/GUIslice/src/GUIslice_drv_adagfx.cpp:1285:5: error: 'm_disp' was not declared in this scope
     m_disp.setFont((const GFXfont *)pFont->pvFont);
     ^~~~~~
/home/admin/Arduino/libraries/GUIslice/src/GUIslice_drv_adagfx.cpp: In function 'void gslc_DrvDrawPoint_base(int16_t, int16_t, uint16_t)':
/home/admin/Arduino/libraries/GUIslice/src/GUIslice_drv_adagfx.cpp:1512:5: error: 'm_disp' was not declared in this scope
     m_disp.drawPixel(nX,nY,nColRaw);
     ^~~~~~
/home/admin/Arduino/libraries/GUIslice/src/GUIslice_drv_adagfx.cpp: In function 'void gslc_DrvDrawLine_base(int16_t, int16_t, int16_t, int16_t, uint16_t)':
/home/admin/Arduino/libraries/GUIslice/src/GUIslice_drv_adagfx.cpp:1522:5: error: 'm_disp' was not declared in this scope
     m_disp.drawLine(nX0,nY0,nX1,nY1,nColRaw);
     ^~~~~~
/home/admin/Arduino/libraries/GUIslice/src/GUIslice_drv_adagfx.cpp: In function 'bool gslc_DrvDrawFillRect(gslc_tsGui*, gslc_tsRect, gslc_tsColor)':
/home/admin/Arduino/libraries/GUIslice/src/GUIslice_drv_adagfx.cpp:1569:5: error: 'm_disp' was not declared in this scope
     m_disp.fillRect(rRect.x,rRect.y,rRect.w,rRect.h,nColRaw);
     ^~~~~~
/home/admin/Arduino/libraries/GUIslice/src/GUIslice_drv_adagfx.cpp: In function 'bool gslc_DrvDrawFillRoundRect(gslc_tsGui*, gslc_tsRect, int16_t, gslc_tsColor)':
/home/admin/Arduino/libraries/GUIslice/src/GUIslice_drv_adagfx.cpp:1581:3: error: 'm_disp' was not declared in this scope
   m_disp.fillRoundRect(rRect.x,rRect.y,rRect.w,rRect.h,nRadius,nColRaw);
   ^~~~~~
/home/admin/Arduino/libraries/GUIslice/src/GUIslice_drv_adagfx.cpp: In function 'bool gslc_DrvDrawFrameRoundRect(gslc_tsGui*, gslc_tsRect, int16_t, gslc_tsColor)':
/home/admin/Arduino/libraries/GUIslice/src/GUIslice_drv_adagfx.cpp:1647:3: error: 'm_disp' was not declared in this scope
   m_disp.drawRoundRect(rRect.x,rRect.y,rRect.w,rRect.h,nRadius,nColRaw);
   ^~~~~~
/home/admin/Arduino/libraries/GUIslice/src/GUIslice_drv_adagfx.cpp: In function 'bool gslc_DrvDrawFrameCircle(gslc_tsGui*, int16_t, int16_t, uint16_t, gslc_tsColor)':
/home/admin/Arduino/libraries/GUIslice/src/GUIslice_drv_adagfx.cpp:1681:3: error: 'm_disp' was not declared in this scope
   m_disp.drawCircle(nMidX,nMidY,nRadius,nColRaw);
   ^~~~~~
/home/admin/Arduino/libraries/GUIslice/src/GUIslice_drv_adagfx.cpp: In function 'bool gslc_DrvDrawFillCircle(gslc_tsGui*, int16_t, int16_t, uint16_t, gslc_tsColor)':
/home/admin/Arduino/libraries/GUIslice/src/GUIslice_drv_adagfx.cpp:1700:3: error: 'm_disp' was not declared in this scope
   m_disp.fillCircle(nMidX,nMidY,nRadius,nColRaw);
   ^~~~~~
/home/admin/Arduino/libraries/GUIslice/src/GUIslice_drv_adagfx.cpp: In function 'bool gslc_DrvDrawFrameTriangle(gslc_tsGui*, int16_t, int16_t, int16_t, int16_t, int16_t, int16_t, gslc_tsColor)':
/home/admin/Arduino/libraries/GUIslice/src/GUIslice_drv_adagfx.cpp:1722:3: error: 'm_disp' was not declared in this scope
   m_disp.drawTriangle(nX0,nY0,nX1,nY1,nX2,nY2,nColRaw);
   ^~~~~~
/home/admin/Arduino/libraries/GUIslice/src/GUIslice_drv_adagfx.cpp: In function 'bool gslc_DrvDrawFillTriangle(gslc_tsGui*, int16_t, int16_t, int16_t, int16_t, int16_t, int16_t, gslc_tsColor)':
/home/admin/Arduino/libraries/GUIslice/src/GUIslice_drv_adagfx.cpp:1744:3: error: 'm_disp' was not declared in this scope
   m_disp.fillTriangle(nX0,nY0,nX1,nY1,nX2,nY2,nColRaw);
   ^~~~~~
/home/admin/Arduino/libraries/GUIslice/src/GUIslice_drv_adagfx.cpp: In function 'bool gslc_DrvRotate(gslc_tsGui*, uint8_t)':
/home/admin/Arduino/libraries/GUIslice/src/GUIslice_drv_adagfx.cpp:3192:5: error: 'm_disp' was not declared in this scope
     m_disp.setRotation(0);
     ^~~~~~

exit status 1

Compilation error: exit status 1`

### Additional info
Waveshare TFT example does output the touch positions via serial. Trying to get any GUISlice example to work to include my own GUI in the next step. Currently I can't get the GUISlice examples working, due to the error above. Any help or push in a direction would be great, kinda stuck.
Is there anything I can do to further debug this? Can you tell what I'm missing here, not sure if I'm the bug here :)

**Comment by Pconti31** [comment]
@gree303 Looks like it can't find this library in Arduino/libraries
[prenticedavid/HX8347D_kbv](https://github.com/prenticedavid/HX8347D_kbv)
Paul--
