### ISSUE TITLE
Touched Items not detected with ESP32-ILI9341-tft_eSPI

### ISSUE THREAD

**Issue by claudchtiscali** [ImpulseAdventure/GUIslice#553]
### Describe the bug
Touch screens seems not working properly. In sketch for example ex46_ard_togglebtn.ino the circular toggle btn is correctly detected while the rectangular is not detected at all. If I move the rectangular at the same Y coordinate as circular (i.e. 100,100,60,30... instead of 230, 150,60,30) it's detected correctly. I get a similar behavior in my own sketch with a more complex GUI.
I'm using Arduino IDE (similar with VSC-PlatformIO)

### Device hardware
- ESP32
- ILI9341 2.8" with XPT2046 controller (HiLetgo 2.8" ILI9341 TFT LCD)
- GUIslice config selected <esp-tftespi-default-xpt2046_int.h>

### Checklist to try first
*Most display/touch issues can be identified by working through the steps in the [Configuring GUIslice](https://github.com/ImpulseAdventure/GUIslice/wiki/Configuring-GUIslice) guide.*
**Done** 

*Please confirm whether:*
- *Display works correctly with standalone display driver library examples (eg. TFT_eSPI graphicstest, Adafruit graphicstest, etc.) without GUIslice:* ???
**Yes with TFT_eSPI, even complex interfaces** 
- *Touch works correctly with standalone touch library examples without GUIslice:* ???
ex02_ard_btn_txt.ino **Works**
ex06_ard_callback.ino **Display work well but neither quit button or check box are detected**
**If I add 2 additional buttons to ex02_ard_btn_txt.ino as follows
  pElemRef = gslc_ElemCreateBtnTxt(&m_gui,E_ELEM_BTN_QUIT0,E_PG_MAIN,
    (gslc_tsRect){120,50,80,40},(char*)"Quit 0",0,E_FONT_BTN,&CbBtnQuit0);

  pElemRef = gslc_ElemCreateBtnTxt(&m_gui,E_ELEM_BTN_QUIT1,E_PG_MAIN,
    (gslc_tsRect){120,100,80,40},(char*)"Quit 1",0,E_FONT_BTN,&CbBtnQuit1);

  pElemRef = gslc_ElemCreateBtnTxt(&m_gui,E_ELEM_BTN_QUIT2,E_PG_MAIN,
    (gslc_tsRect){120,150,80,40},(char*)"Quit 2",0,E_FONT_BTN,&CbBtnQuit2);

if I touch E_ELEM_BTN_QUIT0 it's detected as E_ELEM_BTN_QUIT2 and viceversa**

### Expected behavior
Detect touch items correctly

### Initialization messages
No messages

### Additional info
*Add any other context about the problem here.*

**Comment by Pconti31** [comment]
@claudchtiscali Have you run [diag_ard_touch_calib](https://github.com/ImpulseAdventure/GUIslice/tree/master/examples/arduino/diag_ard_touch_calib) first?
Paul--

**Comment by Pconti31** [comment]
@claudchtiscali Sorry, I just noticed you are using the TFT_eSPI internal XPT2046 touch driver so running calibration won't help.

**Comment by Pconti31** [comment]
@claudchtiscali Two things to try,
1- uncomment inside your esp-tftespi-default-xpt2046_int.h and check serial output as you touch the screen
```
//#define DBG_TOUCH         // Enable debugging of touch-presses
```
2- turn off the internal touch driver inside your TFT_eSPI's User_Setup.h by commenting out TOUCH_CS
download [PaulStoffregen/XPT2046_Touchscreen](https://github.com/PaulStoffregen/XPT2046_Touchscreen)
 and switch to using esp-tftespi-default-xpt2046.h after editing it to match your touch pins.
Then run [diag_ard_touch_calib](https://github.com/ImpulseAdventure/GUIslice/tree/master/examples/arduino/diag_ard_touch_calib)
and edit the various #define ADATOUCH_X_* and #define ADATOUCH_Y_* inside esp-tftespi-default-xpt2046.h and rerun your test apps.

Paul--

**Comment by claudchtiscali** [comment]
Thanks Paul.
I did everything you suggested and with new #define ADATOUCH_X_* and #define ADATOUCH_Y_* inside esp-tftespi-default-xpt2046.h it works.

Cheers
Claudio
