### ISSUE TITLE
Maybe a typo for  #elif defined(DRV_TOUCH_ADA_SIMPLE)

### ISSUE THREAD

**Issue by espHorst** [ImpulseAdventure/GUIslice#56]
When adding the XPT2046 (pull request "Adding rotation depending display width and heigth setting for ILI9341") I copied some code from the DRV_TOUCH_ADA_SIMPLE. Here I'm not sure if the last command below is a typo and should read nRawPress=p.z; instead of nRawPress=p.x;
Best regards.

  #elif defined(DRV_TOUCH_ADA_SIMPLE)

  TSPoint p = m_touch.getPoint();

  pinMode(XM, OUTPUT);
  pinMode(YP, OUTPUT);

  if (p.z > 10 && p.z < 1000) {

    nRawX=p.x;
    nRawY=p.y;
    nRawPress=p.x;

**Comment by ImpulseAdventure** [comment]
Thanks for noticing this... I have made the update now.
