### ISSUE TITLE
Latest commit "Clean up compilation warnings for DRV_TOUCH_NONE" does not work for me

### ISSUE THREAD

**Issue by espHorst** [ImpulseAdventure/GUIslice#60]
Setting: 
#define DRV_TOUCH_XPT2046 

Arduino: 1.8.5 (Linux), Board: "Generic STM32F103C series, STM32F103CB (20k RAM. 128k Flash), BMP (Black Magic Probe), 72Mhz (Normal), Faster (-O2)"
---
/home/goki/Arduino/libraries/GUIslice/src/GUIslice.c: In function 'gslc_ElemEvent':
/home/goki/Arduino/libraries/GUIslice/src/GUIslice.c:1989:7: error: a label can only be part of a statement and a declaration is not a statement
       void*               pvData            = sEvent.pvData;
       ^
/home/goki/Arduino/libraries/GUIslice/src/GUIslice.c:1990:7: error: expected expression before 'gslc_tsElemRef'
       gslc_tsElemRef*     pElemRefTracked   = NULL;
       ^
/home/goki/Arduino/libraries/GUIslice/src/GUIslice.c:2000:7: error: 'pElemRefTracked' undeclared (first use in this function)
       pElemRefTracked = pElemRef;
       ^
/home/goki/Arduino/libraries/GUIslice/src/GUIslice.c:2000:7: note: each undeclared identifier is reported only once for each function it appears in
/home/goki/Arduino/libraries/GUIslice/src/GUIslice.c: In function 'gslc_InitTouch':
/home/goki/Arduino/libraries/GUIslice/src/GUIslice.c:2921:3: warning: implicit declaration of function 'gslc_TDrvInitTouch' [-Wimplicit-function-declaration]
   bOk = gslc_TDrvInitTouch(pGui,acDev);
   ^
/home/goki/Arduino/libraries/GUIslice/src/GUIslice.c: In function 'gslc_GetTouch':
/home/goki/Arduino/libraries/GUIslice/src/GUIslice.c:2946:3: warning: implicit declaration of function 'gslc_TDrvGetTouch' [-Wimplicit-function-declaration]
   return gslc_TDrvGetTouch(pGui,pnX,pnY,pnPress);
   ^
...
Error compiling for board Generic STM32F103C series.

**Comment by ImpulseAdventure** [comment]
My apologies @espHorst I think you just caught me after a briefly mistaken commit. That section was updated immediately afterwards, so if you could recheck now that would be great. thanks!

**Comment by espHorst** [comment]
Works like a charm! Thanks a lot! I really like the library - so easy to do small GUIs on my STM32 ...

**Comment by ImpulseAdventure** [comment]
Glad to hear it! Thanks for the confirmation
