### ISSUE TITLE
Compiler Warning "may be incompatible with your current board which runs on (STM32F1)"

### ISSUE THREAD

**Issue by espHorst** [ImpulseAdventure/GUIslice#67]
Hi ImpulseAdventure.

since the aeb6100c62e6dadccf4cc876e29f6cc4519e9ae8 commit the GUIslice examples are under INCOMPATIBLE and I get the follwing compiler warning:

WARNING: library GUIslice claims to run on (avr, esp8266, esp32, stm32, samd) architecture(s) and may be incompatible with your current board which runs on (STM32F1) architecture(s).

Adding STM32F1 in the libaries.poperties file solves the issue.
The resulting line for architectures is then

architectures=avr,esp8266,esp32,stm32,samd,STM32F1

I don't know if the stm32 is useful or required.
Best regards.

**Comment by ImpulseAdventure** [comment]
Fixed. I have seen a lot of variability in how the architectures property has been enumerated across other libraries (many just use `stm32`). I have now added the more specific `STM32F1` which should address the warning.
