### ISSUE TITLE
gslc_DrvRotateSwapFlip() does not exchange nDispW and nDispH

### ISSUE THREAD

**Issue by espHorst** [ImpulseAdventure/GUIslice#68]
using the dynamic gslc_DrvRotateSwapFlip() does not work for me going from landscape to portrait.
The function does not exchange 
pGui->nDispW
pGui->nDispH
in the case that the swap setting changes.
I can try to do a PR fixing this taking in mind that this also requires an update of
// Defaults for clipping region
gslc_tsRect rClipRect = {0,0,pGui->nDispW,pGui->nDispH};
gslc_DrvSetClipRect(pGui,&rClipRect);

**Comment by espHorst** [comment]
I will give it a try!

**Comment by ImpulseAdventure** [comment]
Dynamic rotation feature has been implemented via the new `GuiRotate()` command.
Closing as implemented by PR #72
