### ISSUE TITLE
Arduino does not work after e3541cd353a8efbfbb60d903e825e3c2c3abaa1a

### ISSUE THREAD

**Issue by espHorst** [ImpulseAdventure/GUIslice#69]
Since 
e3541cd353a8efbfbb60d903e825e3c2c3abaa1a Fix-potential-crash-in-FontAdd()-if-LINUX-font-file-doesn't-exist
Arduino does not work any more.

This is because
```
const void* gslc_DrvFontAdd(gslc_teFontRefType eFontRefType,const void* pvFontRef,uint16_t nFontSz)
{
  // Arduino mode currently only supports font definitions from memory
  if (eFontRefType != GSLC_FONTREF_PTR) {
    GSLC_DEBUG_PRINT("ERROR: DrvFontAdd(%s) failed - Arduino only supports memory-based fonts\n","");
    return NULL;
  }
  // Return pointer to Adafruit-GFX GFXfont structure
  return pvFontRef;
}
```
returns null for Arduino and 
e3541cd353a8efbfbb60d903e825e3c2c3abaa1a
adds
`    const void* pvFont = gslc_DrvFontAdd(eFontRefType,pvFontRef,nFontSz);
    if (pvFont == NULL) {
      return false;
`
in GUIslice.c

**Comment by ImpulseAdventure** [comment]
My sincere apologies, @espHorst ! Clearly I had overlooked the way in which `pvFontRef` gets used in `FontAdd()` for the base Arduino mode.

Despite having clean compile-based regressions, this reaffirms the need to continue the frequent manual touch tests. Ironically enough, I am currently looking into ways that I can perform automated runtime regressions as well. I believe I have a solution for the LINUX targets, but haven't figured out a good way to do the same for Arduino-specific code yet.

For this particular issue, I will perform an audit of the various ways in which font references get used (especially now that anti-aliased fonts are also in the works), and document these in the wiki to avoid future errors.

Thanks again!
