### ISSUE TITLE
Wiki documentation for examples & elements

### ISSUE THREAD

**Issue by ImpulseAdventure** [ImpulseAdventure/GUIslice#78]
As the number of examples has grown, it would be helpful to create a set of pages in the wiki to show what each of the examples look like and the features that each demonstrates.

In addition, a gallery of each element type should also be provided.

**Comment by espHorst** [comment]
Would it be possible to extend the name of each example by a short word describing the example? E.g. adding "_rotate" or "_touch_handler" ... ? This would really help in remembering the examples when choosing them from the arduino IDE without the need to open each time the wiki.

**Comment by ImpulseAdventure** [comment]
Sounds reasonable. I will be updating the `README.md` in each of the examples directory to include an a basic description of each example. However, renaming the directories to include the general function (unfortunately eliminating the visible git changelog in the process) would be worthwhile as it would also address offline identification.

**Comment by ImpulseAdventure** [comment]
Initial list of examples has been added to the wiki: (more details & screenshots to be added later)
[Wiki: GUIslice Gallery of Included Examples](https://github.com/ImpulseAdventure/GUIslice/wiki/Gallery-of-Examples)

**Comment by ImpulseAdventure** [comment]
Completed renaming of all examples to use a descriptive name in the title.
This should make it much easier to locate a specific example.
