### ISSUE TITLE
Builder: Scrollbars for when Simulated Panel is larger than available window

### ISSUE THREAD

**Issue by rrroonn** [ImpulseAdventure/GUIslice#93]
Hi,

It would be good to have scrollbars.  If you zoom in then you cannot access all of the display area.

thanks,

Ron

**Comment by ImpulseAdventure** [comment]
Update: Paul has indicated to me that this feature (scrollbars on the Builder design canvas) has now been implemented in Builder 0.11.0-rc1. Thanks @rrroonn for the feature suggestion.
