### ISSUE TITLE
Builder: Selecting component in Tree View should/could select item for editing

### ISSUE THREAD

**Issue by rrroonn** [ImpulseAdventure/GUIslice#94]
It would be nice to be able to click on an item in the Tree View and have it bring that component into focus and show its properties.  This would be especially useful when components are not visible due to Z order.

An alternative would be to have a dropdown list of components (on current page?) in the Properties area.

thank you

Ron

**Comment by rrroonn** [comment]
Funny, I restarted app and now this does work.  Not sure of what the conditions are to break this function.  Will keep and eye on it.

**Comment by Pconti31** [comment]
Let us know if you find a way to reproduce this condition.

**Comment by rrroonn** [comment]
That project that I uploaded for bad code generation has that issue on PG_MAIN - can't select anything though.  Maybe similar symptom but different cause.

**Comment by ImpulseAdventure** [comment]
Closing as the selection feature is currently implemented and the treeview non-selection behavior does not appear to be reproducible at the moment. If it recurs, please feel free to add a followup comment and we can reopen for investigation. Thanks!
